[project]
name = "langchain-course"
version = "0.1.0"
description = "LangChain course project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.27",
    "langchain-openai>=0.3.33",
    "langchain-community>=0.3.27",
    "python-dotenv>=1.1.1",
    "langchain-tavily>=0.2.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools]
py-modules = ["hello","validate_env"]